### ISSUE TITLE
test INSTALL 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#107]
Please test installation of DK v3 frontend 
on your local machine 
follwoing step by step the installation instructions 
and let us know if the documentation is complete and if went smooth

**Comment by mstyle21** [comment]
Everything went smooth, accordingly to the documentation, only exception was npm install which ended with saying that package "pre-commit":"1.12" could not be installed, but it was caused by permission issues regarding npm installation, so after some research i found and recommend installing npm through Node Version Manager which will remove the issues of permissions of npm and node modules

**Comment by arhimede** [comment]
can you correct the readme.md file and add the instructiosn line by line related to npm ?

https://github.com/dotkernel/frontend/blob/3.0/README.md

**Comment by bidi47** [comment]
the readme has been updated
