### ISSUE TITLE
remove laminas-rbac ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#159]
and regrenerate composer.josn and other relatd files

**Comment by Calin23** [comment]
I removed Mezzio AuthorizationInterface and replaced it with Dot AuthorizationInterface from dependencies.global.php, because authorization is now managed by dot-rbac, now we can access itGranted if a class implements Dot AuthorizationInterface. I changed AuthorizationInterface from dot-twigrenderer, so we can now access the isGranted method also from the twig extension class .
