### ISSUE TITLE
Replace twig exgtensions

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#204]
https://github.com/twigphp/Twig-extensions

Is abandoned 

let's see what else we can use

**Comment by Calin23** [comment]
We have to remove twig extension since it is **deprecated**, there are several solutions, such as replace it with  _twig / extra-bundle_ which is not a recommended solution because it uses more symphony packages, the second solution is  we create the two extensions that we currently use _I18nExtension_ that deals with translations as well as _DateExtension_ for formatting the date and put them somewhere in _/ App_ or a better option to move them in the _dot / twig-renderer_ package in the _Extension_ folder.
