### ISSUE TITLE
update phpcs.xml in repo

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#372]
https://github.com/mezzio/mezzio/blob/3.17.x/phpcs.xml

to reflect the latest version inherited from mezzio

**Comment by alexmerlin** [comment]
Issue is already fixed, I'm using it to fix another bug introduced by fixing this issue.
Based on my [review](https://github.com/dotkernel/frontend/pull/378#pullrequestreview-1480653530), one of the tasks was to:

> phpcs.xml.dist: make it identical with phpcs.xml

Accidentally, instead of [phpcs.xml.dist](https://github.com/dotkernel/frontend/blob/4.0/phpcs.xml.dist), the contents of [phpunit.xml.dist](https://github.com/dotkernel/frontend/blob/4.0/phpunit.xml.dist) were replaced with the ones of [phpcs.xml](https://github.com/dotkernel/frontend/blob/4.0/phpcs.xml)

The new tasks are:

- [ ] phpcs.xml.dist: make it identical with phpcs.xml
- [ ] revert phpunit.xml.dist to its original form
