### ISSUE TITLE
update static analysis actions 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#420]
currently we are using v3 

we are getting the message 
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

I presume the actions/checkout@v3, actions/cache@v3 need to be changed to something else 
** all over the packages which use node.js *

**Comment by alexmerlin** [comment]
As described in their blog link, they are transitioning from Node 16 (`actions/package@v3`) to Node 20 (`actions/package@v4`).
We need to update all `dot-*` packages and all our projects to use v4 of both [actions/cache](https://github.com/actions/cache) and [action/checkout](https://github.com/actions/checkout).

In order to avoid in the future running again through all packages/projects, we should create our CI repo like Laminas does in their packages.

See [here](https://github.com/laminas/laminas-servicemanager/blob/3.23.x/.github/workflows/continuous-integration.yml#L11C11-L11C50) an example of how they use their CI repo.
See [here](https://github.com/laminas/workflow-continuous-integration) their CI repo.

**Comment by alexmerlin** [comment]
`actions/checkout@v4` runs on Node `20.x`
but
`actions/cache@v4` is still on Node `16.x`

Issue: https://github.com/actions/cache/issues/1323
PR: https://github.com/actions/cache/pull/1326
Once PR is merged, we can resume work on this.
