### ISSUE TITLE
twig code style ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#432]
https://github.com/VincentLanglet/Twig-CS-Fixer

we should investigate if we want to enforece a twig code style in phpstorm and in CI actions

**Comment by bidi47** [comment]
tested locally, ran these two
- composer require --dev vincentlanglet/twig-cs-fixer
- vendor/bin/twig-cs-fixer lint src/

complains about 'trans' extension, e.g.
- File is invalid: Unknown "trans" tag.
- File is invalid: Unexpected "trans" tag (expecting closing tag for the "for" tag defined near line 24)

no impact for phpcs or psalm

the updated files can be reviewed here
https://github.com/dotkernel/frontend/compare/issue-432?expand=1

the translation feature is set to be removed or replaced in https://github.com/dotkernel/frontend/issues/445, so that's a blocker for this issue

**Comment by bidi47** [comment]
investigating a way to handle extensions, to pass the tests
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md#token-parsers--more

**Comment by bidi47** [comment]
- added our extensions DateExtension, TranslationExtension
- ran the check again (no directory to check every twig file) `vendor/bin/twig-cs-fixer lint`
- ran the autofix `vendor/bin/twig-cs-fixer lint --fix`
see the result here https://github.com/dotkernel/frontend/compare/issue-432?expand=1

**Comment by alexmerlin** [comment]
- must `.twig-cs-fixer.php` be stored in the root of the project?
- `.twig-cs-fixer.cache` should be gitignored?

**Comment by bidi47** [comment]
> * must `.twig-cs-fixer.php` be stored in the root of the project?

the config file location is relevant for where you run the check from
the alternative (if we want to move it) is to run the command with the config path
`vendor/bin/twig-cs-fixer lint --config=dir/.twig-cs-fixer.php /path/to/code`
**where would be a better place for it?**

>     * `.twig-cs-fixer.cache` should be gitignored?

i'll add this to the list

**Comment by alexmerlin** [comment]
> the config file location is relevant for where you run the check from the alternative (if we want to move it) is to run the command with the config path `vendor/bin/twig-cs-fixer lint --config=dir/.twig-cs-fixer.php /path/to/code` **where would be a better place for it?**

So `.twig-cs-fixer.php` is a config file. Then it should be stored in the `config` directory.
We could create a composer script (see [scripts](https://github.com/dotkernel/frontend/blob/5.0/composer.json#L100)) that runs the command with `--config=config/twig-cs-fixer.php` appended.
